#!/usr/bin/env python3
"""
Operation Neptune static recompilation pipeline

Orchestrates: PE analysis -> disassembly -> function discovery -> lifting -> C output
Uses pcrecomp tools from ../tools/ (the sibling checkout of the toolkit).
"""

import os
import sys
import json
import time
import argparse

# Add pcrecomp to path
PCRECOMP_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', 'tools'))
sys.path.insert(0, PCRECOMP_ROOT)

from tools.pe.pe_analyze import analyze_pe, build_iat_map, export_json
from tools.disasm.disasm32 import Disassembler
from tools.lift.lift32 import Lifter


def load_pe(filepath):
    """Load and analyze a PE file."""
    print(f"[*] Analyzing PE: {filepath}")
    info = analyze_pe(filepath)

    with open(filepath, 'rb') as f:
        pe_data = f.read()

    iat_map = build_iat_map(info)
    print(f"[*] Image base: 0x{info.image_base:08X}")
    print(f"[*] Code: 0x{info.code_start:08X} - 0x{info.code_end:08X}")
    print(f"[*] Data: 0x{info.data_start:08X} - 0x{info.data_end:08X}")
    print(f"[*] IAT entries: {len(iat_map)}")

    return info, pe_data, iat_map


def discover_functions(pe_data, info, iat_map):
    """Discover all functions via recursive descent disassembly."""
    disasm = Disassembler(pe_data, info.image_base, info.sections)
    functions = disasm.find_functions(info.code_start, info.code_end, iat_map)
    return functions


def generate_function_list(functions, output_path):
    """Export function list to JSON."""
    func_list = []
    for addr, func in sorted(functions.items()):
        func_list.append({
            'address': f"0x{addr:08X}",
            'address_int': addr,
            'name': func.name,
            'size': func.size,
            'num_blocks': len(func.blocks),
            'num_instructions': func.num_instructions,
            'is_thunk': func.is_thunk,
            'calls_to': [f"0x{t:08X}" for t in sorted(func.calls_to)],
        })

    with open(output_path, 'w') as f:
        json.dump(func_list, f, indent=2)
    print(f"[*] Exported {len(func_list)} functions to {output_path}")


def generate_import_stubs(iat_map, output_path):
    """Generate stub implementations for imported functions."""
    by_dll = {}
    for va, (dll, name) in sorted(iat_map.items()):
        by_dll.setdefault(dll, []).append((va, name))

    with open(output_path, 'w') as f:
        f.write("/* Import bridge stubs -- auto-generated */\n\n")
        f.write('#include "recomp_types.h"\n\n')

        for dll, imports in sorted(by_dll.items()):
            f.write(f"\n/* ===== {dll} ===== */\n\n")
            for va, name in imports:
                f.write(f"/* 0x{va:08X} */ void bridge_{name}(void) {{\n")
                f.write(f"    /* TODO: implement {dll}::{name} */\n")
                f.write(f"    STUB(\"{dll}::{name}\");\n")
                f.write(f"}}\n\n")

    print(f"[*] Generated import stubs for {sum(len(v) for v in by_dll.values())} imports")


def generate_recomp_files(functions, iat_map, output_dir, split_size=1000, func_names=None):
    """Generate recompiled C source files."""
    os.makedirs(output_dir, exist_ok=True)

    # Clear previous output first. A run producing fewer files than the last one
    # leaves stale recomp_*.c behind, and the CMake glob happily compiles them
    # alongside the new ones -- duplicate definitions of functions that no
    # longer exist.
    import glob as _glob
    for stale in _glob.glob(os.path.join(output_dir, 'recomp_[0-9]*.c')):
        os.remove(stale)

    for addr, nm in (func_names or {}).items():
        if addr in functions:
            functions[addr].name = nm
    lifter = Lifter(iat_map=iat_map, func_names=func_names or {},
                    lifted=set(functions.keys()),
                    # cmp/sbb/neg is how MGL returns success; the stale-_cf
                    # reading makes those returns arbitrary.
                    precise_sbb=True)

    sorted_funcs = sorted(functions.values(), key=lambda f: f.address)
    total = len(sorted_funcs)
    print(f"[*] Generating C code for {total} functions...")

    file_idx = 0
    func_idx = 0
    all_func_names = []

    while func_idx < total:
        chunk = sorted_funcs[func_idx:func_idx + split_size]
        filename = f"recomp_{file_idx:04d}.c"
        filepath = os.path.join(output_dir, filename)

        with open(filepath, 'w') as f:
            f.write(f"/* Auto-generated by the Operation Neptune recompiler -- DO NOT EDIT */\n")
            f.write(f"/* Functions {func_idx} to {func_idx + len(chunk) - 1} */\n")
            f.write(f"/* Address range: 0x{chunk[0].address:08X} - 0x{chunk[-1].address:08X} */\n\n")
            f.write(f'#define RECOMP_GENERATED_CODE\n')
            f.write(f'#include "recomp_types.h"\n')
            f.write(f'#include "recomp_funcs.h"\n')
            f.write(f'#include <math.h>\n')
            f.write(f'#include <string.h>\n\n')

            for func in chunk:
                try:
                    code = lifter.lift_function(func)
                    f.write(code)
                    f.write('\n\n')
                    all_func_names.append((func.address, func.name))
                except Exception as e:
                    f.write(f"/* ERROR lifting {func.name}: {e} */\n")
                    f.write(f"void {func.name}(void) {{ /* FAILED */ }}\n\n")
                    all_func_names.append((func.address, func.name))

        func_idx += len(chunk)
        file_idx += 1

        if file_idx % 5 == 0:
            print(f"[*] Generated {func_idx}/{total} functions ({file_idx} files)...")

    print(f"[*] Generated {file_idx} source files in {output_dir}")

    # Generate forward declarations header
    header_path = os.path.join(output_dir, "recomp_funcs.h")
    with open(header_path, 'w') as f:
        f.write("/* Auto-generated function declarations -- DO NOT EDIT */\n")
        f.write("#pragma once\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write(f"/* {len(all_func_names)} recompiled functions */\n\n")
        for addr, name in all_func_names:
            f.write(f"void {name}(void);  /* 0x{addr:08X} */\n")

    # Generate dispatch table
    dispatch_path = os.path.join(output_dir, "recomp_dispatch.c")
    with open(dispatch_path, 'w') as f:
        f.write("/* Auto-generated dispatch table -- DO NOT EDIT */\n\n")
        f.write('#include "recomp_types.h"\n')
        f.write('#include "recomp_funcs.h"\n\n')
        f.write(f"const recomp_dispatch_entry_t recomp_dispatch_table[] = {{\n")
        for addr, name in sorted(all_func_names, key=lambda x: x[0]):
            f.write(f"    {{ 0x{addr:08X}u, {name} }},\n")
        f.write(f"}};\n\n")
        f.write(f"const uint32_t recomp_dispatch_count = {len(all_func_names)};\n")

    print(f"[*] Generated dispatch table with {len(all_func_names)} entries")
    return all_func_names


def main():
    parser = argparse.ArgumentParser(description='Operation Neptune static recompilation pipeline')
    parser.add_argument('pe_file', help='Path to game executable')
    parser.add_argument('--output', '-o', default='src/recomp/gen',
                        help='Output directory for generated code')
    parser.add_argument('--split', type=int, default=1000,
                        help='Max functions per source file')
    parser.add_argument('--all', action='store_true',
                        help='Run full pipeline (analyze + disassemble + lift)')
    parser.add_argument('--analyze-only', action='store_true',
                        help='Only run PE analysis')
    parser.add_argument('--discover-only', action='store_true',
                        help='Run PE analysis + function discovery only')
    parser.add_argument('--functions-json', default=None,
                        help='Export function list to JSON')
    parser.add_argument('--stubs', default=None,
                        help='Generate import stub file')
    parser.add_argument('--pe-json', default=None,
                        help='Export PE analysis to JSON')
    parser.add_argument('--names', default=None,
                        help='JSON of VA -> {name, module} from tools/name_functions.py; '
                             'lifted functions get these names instead of sub_XXXXXXXX')

    args = parser.parse_args()

    start_time = time.time()

    # Step 1: PE analysis
    info, pe_data, iat_map = load_pe(args.pe_file)

    if args.pe_json:
        export_json(info, args.pe_json)

    if args.analyze_only:
        from tools.pe.pe_analyze import print_summary
        print_summary(info)
        return

    # Step 2: Function discovery
    print(f"\n[*] Phase 2: Function discovery...")
    functions = discover_functions(pe_data, info, iat_map)
    print(f"[*] Found {len(functions)} functions")

    if args.functions_json:
        generate_function_list(functions, args.functions_json)

    if args.stubs:
        os.makedirs(os.path.dirname(args.stubs), exist_ok=True)
        generate_import_stubs(iat_map, args.stubs)

    if args.discover_only:
        elapsed = time.time() - start_time
        print(f"\n[*] Discovery complete in {elapsed:.1f}s")
        return

    if args.all:
        # Step 3: Code generation
        print(f"\n[*] Phase 3: Code generation...")
        func_names = {}
        if args.names:
            with open(args.names) as f:
                for va, v in json.load(f).items():
                    name = v['name'] if isinstance(v, dict) else v
                    mod = v.get('module') if isinstance(v, dict) else None
                    # Keep the address in the symbol: two modules can hold a
                    # function of the same name, and a name that collides is
                    # worse than one that is merely ugly.
                    func_names[int(va, 16)] = f"{mod}_{name}" if mod else name
            print(f"[*] {len(func_names)} functions will be named from {args.names}")

        all_funcs = generate_recomp_files(
            functions, iat_map, args.output,
            split_size=args.split, func_names=func_names,
        )

        elapsed = time.time() - start_time
        print(f"\n[*] Complete! {len(functions)} functions recompiled in {elapsed:.1f}s")
        print(f"[*] Output: {args.output}")

    elapsed = time.time() - start_time
    print(f"\n[*] Total time: {elapsed:.1f}s")


if __name__ == '__main__':
    main()
